#!/bin/bash

showdicker()
{
	echo -ne ' 8'
	for i in $(seq 1 $(($(tput cols)-8))); do echo -ne =; sleep 0.005; done
	echo 'D~~~ '
}

DOCKERBIN=$(which docker 2>/dev/null)

if [ -z "$DOCKERBIN" ];
then
	DOCKERBIN=$(which podman 2>/dev/null)
fi

if [ -z "$DOCKERBIN" ];
then
	DOCKERBIN=$(which nerdctl 2>/dev/null)
fi

if [ -z "$DOCKERBIN" ];
then
	DOCKERBIN="docker"
fi

showdicker
$DOCKERBIN $@
showdicker

