name: create package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: dicker
          version: ${{ github.event.release.tag_name }}
          arch: amd64
          format: deb
          package: package.yaml
      - name: Upload deb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true
      - uses: kentik/pkg@v1.0.0-rc6
        with:
          name: dicker
          version: ${{ github.event.release.tag_name }}
          arch: x86_64
          format: rpm
          package: package.yaml
      - name: Upload RPM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
          file_glob: true